// AceShell 插件协议 v1 —— 跨语言契约 (Go / 其他语言经 gRPC 实现)
//
// 双向服务:
//   - AcePlugin  : 插件进程实现, 宿主调用 (钩子: 生命周期/侧栏显隐/标签页事件/通用 Rpc)
//   - HostService: 宿主进程实现, 插件调用 (能力: 开/关标签页/改标题/Toast/会话清单)
//
// 非宿主侧鉴权: 插件调用 HostService 时须携带 metadata "x-aceshell-token"
// (Start 时由宿主下发的一次性随机令牌)。
//
// 重新生成 (仅协议变更时):
//   go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.12
//   go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
//   go install github.com/bufbuild/buf/cmd/buf@latest
//   buf generate proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: aceshell.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AcePlugin_Info_FullMethodName          = "/aceshell.plugin.v1.AcePlugin/Info"
	AcePlugin_Start_FullMethodName         = "/aceshell.plugin.v1.AcePlugin/Start"
	AcePlugin_Shutdown_FullMethodName      = "/aceshell.plugin.v1.AcePlugin/Shutdown"
	AcePlugin_OnViewVisible_FullMethodName = "/aceshell.plugin.v1.AcePlugin/OnViewVisible"
	AcePlugin_OnViewHidden_FullMethodName  = "/aceshell.plugin.v1.AcePlugin/OnViewHidden"
	AcePlugin_OnTabEvent_FullMethodName    = "/aceshell.plugin.v1.AcePlugin/OnTabEvent"
	AcePlugin_Rpc_FullMethodName           = "/aceshell.plugin.v1.AcePlugin/Rpc"
)

// AcePluginClient is the client API for AcePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AcePluginClient interface {
	// 返回插件元数据 (侧栏视图注册清单等)。宿主在握手后立即调用。
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*PluginInfo, error)
	// 生命周期开始。HostContext 携带宿主版本、插件私有数据目录与 HostService 端点/令牌。
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	// 生命周期结束。宿主退出/插件被禁用/更新前调用, 插件应尽快收尾。
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	// 侧栏面板可见性变化 (首次显示/隐藏都会通知)。
	OnViewVisible(ctx context.Context, in *ViewVisibleRequest, opts ...grpc.CallOption) (*ViewVisibleResponse, error)
	OnViewHidden(ctx context.Context, in *ViewHiddenRequest, opts ...grpc.CallOption) (*ViewHiddenResponse, error)
	// 标签页事件: opened(宿主已创建) / activated(被激活) / closed(用户关闭)。
	OnTabEvent(ctx context.Context, in *TabEvent, opts ...grpc.CallOption) (*TabEventResponse, error)
	// 通用业务通道: 插件前端 (经宿主转发) 与宿主扩展能力都走这里, JSON 进出。
	Rpc(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcResponse, error)
}

type acePluginClient struct {
	cc grpc.ClientConnInterface
}

func NewAcePluginClient(cc grpc.ClientConnInterface) AcePluginClient {
	return &acePluginClient{cc}
}

func (c *acePluginClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, AcePlugin_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *acePluginClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, AcePlugin_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *acePluginClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, AcePlugin_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *acePluginClient) OnViewVisible(ctx context.Context, in *ViewVisibleRequest, opts ...grpc.CallOption) (*ViewVisibleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewVisibleResponse)
	err := c.cc.Invoke(ctx, AcePlugin_OnViewVisible_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *acePluginClient) OnViewHidden(ctx context.Context, in *ViewHiddenRequest, opts ...grpc.CallOption) (*ViewHiddenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewHiddenResponse)
	err := c.cc.Invoke(ctx, AcePlugin_OnViewHidden_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *acePluginClient) OnTabEvent(ctx context.Context, in *TabEvent, opts ...grpc.CallOption) (*TabEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TabEventResponse)
	err := c.cc.Invoke(ctx, AcePlugin_OnTabEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *acePluginClient) Rpc(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcResponse)
	err := c.cc.Invoke(ctx, AcePlugin_Rpc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AcePluginServer is the server API for AcePlugin service.
// All implementations must embed UnimplementedAcePluginServer
// for forward compatibility.
type AcePluginServer interface {
	// 返回插件元数据 (侧栏视图注册清单等)。宿主在握手后立即调用。
	Info(context.Context, *InfoRequest) (*PluginInfo, error)
	// 生命周期开始。HostContext 携带宿主版本、插件私有数据目录与 HostService 端点/令牌。
	Start(context.Context, *StartRequest) (*StartResponse, error)
	// 生命周期结束。宿主退出/插件被禁用/更新前调用, 插件应尽快收尾。
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	// 侧栏面板可见性变化 (首次显示/隐藏都会通知)。
	OnViewVisible(context.Context, *ViewVisibleRequest) (*ViewVisibleResponse, error)
	OnViewHidden(context.Context, *ViewHiddenRequest) (*ViewHiddenResponse, error)
	// 标签页事件: opened(宿主已创建) / activated(被激活) / closed(用户关闭)。
	OnTabEvent(context.Context, *TabEvent) (*TabEventResponse, error)
	// 通用业务通道: 插件前端 (经宿主转发) 与宿主扩展能力都走这里, JSON 进出。
	Rpc(context.Context, *RpcRequest) (*RpcResponse, error)
	mustEmbedUnimplementedAcePluginServer()
}

// UnimplementedAcePluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAcePluginServer struct{}

func (UnimplementedAcePluginServer) Info(context.Context, *InfoRequest) (*PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedAcePluginServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedAcePluginServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedAcePluginServer) OnViewVisible(context.Context, *ViewVisibleRequest) (*ViewVisibleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnViewVisible not implemented")
}
func (UnimplementedAcePluginServer) OnViewHidden(context.Context, *ViewHiddenRequest) (*ViewHiddenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnViewHidden not implemented")
}
func (UnimplementedAcePluginServer) OnTabEvent(context.Context, *TabEvent) (*TabEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnTabEvent not implemented")
}
func (UnimplementedAcePluginServer) Rpc(context.Context, *RpcRequest) (*RpcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rpc not implemented")
}
func (UnimplementedAcePluginServer) mustEmbedUnimplementedAcePluginServer() {}
func (UnimplementedAcePluginServer) testEmbeddedByValue()                   {}

// UnsafeAcePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AcePluginServer will
// result in compilation errors.
type UnsafeAcePluginServer interface {
	mustEmbedUnimplementedAcePluginServer()
}

func RegisterAcePluginServer(s grpc.ServiceRegistrar, srv AcePluginServer) {
	// If the following call panics, it indicates UnimplementedAcePluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AcePlugin_ServiceDesc, srv)
}

func _AcePlugin_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcePluginServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcePlugin_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcePluginServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcePlugin_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcePluginServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcePlugin_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcePluginServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcePlugin_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcePluginServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcePlugin_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcePluginServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcePlugin_OnViewVisible_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewVisibleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcePluginServer).OnViewVisible(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcePlugin_OnViewVisible_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcePluginServer).OnViewVisible(ctx, req.(*ViewVisibleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcePlugin_OnViewHidden_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewHiddenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcePluginServer).OnViewHidden(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcePlugin_OnViewHidden_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcePluginServer).OnViewHidden(ctx, req.(*ViewHiddenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcePlugin_OnTabEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TabEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcePluginServer).OnTabEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcePlugin_OnTabEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcePluginServer).OnTabEvent(ctx, req.(*TabEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcePlugin_Rpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcePluginServer).Rpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcePlugin_Rpc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcePluginServer).Rpc(ctx, req.(*RpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AcePlugin_ServiceDesc is the grpc.ServiceDesc for AcePlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AcePlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aceshell.plugin.v1.AcePlugin",
	HandlerType: (*AcePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _AcePlugin_Info_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _AcePlugin_Start_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _AcePlugin_Shutdown_Handler,
		},
		{
			MethodName: "OnViewVisible",
			Handler:    _AcePlugin_OnViewVisible_Handler,
		},
		{
			MethodName: "OnViewHidden",
			Handler:    _AcePlugin_OnViewHidden_Handler,
		},
		{
			MethodName: "OnTabEvent",
			Handler:    _AcePlugin_OnTabEvent_Handler,
		},
		{
			MethodName: "Rpc",
			Handler:    _AcePlugin_Rpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aceshell.proto",
}

const (
	HostService_OpenTab_FullMethodName      = "/aceshell.plugin.v1.HostService/OpenTab"
	HostService_CloseTab_FullMethodName     = "/aceshell.plugin.v1.HostService/CloseTab"
	HostService_SetTabTitle_FullMethodName  = "/aceshell.plugin.v1.HostService/SetTabTitle"
	HostService_ShowToast_FullMethodName    = "/aceshell.plugin.v1.HostService/ShowToast"
	HostService_ListSessions_FullMethodName = "/aceshell.plugin.v1.HostService/ListSessions"
	HostService_EmitUIEvent_FullMethodName  = "/aceshell.plugin.v1.HostService/EmitUIEvent"
)

// HostServiceClient is the client API for HostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostServiceClient interface {
	// 打开标签页 (tabKey 幂等: 已存在则激活并返回现有 ID)。
	// 组件 componentId 必须是插件前端 entry.js 导出 components 中的键。
	OpenTab(ctx context.Context, in *OpenTabRequest, opts ...grpc.CallOption) (*OpenTabResponse, error)
	// 按 tabKey 关闭标签页。返回是否找到并已请求关闭。
	CloseTab(ctx context.Context, in *CloseTabRequest, opts ...grpc.CallOption) (*CloseTabResponse, error)
	SetTabTitle(ctx context.Context, in *SetTabTitleRequest, opts ...grpc.CallOption) (*SetTabTitleResponse, error)
	// 宿主内 Toast 提示。level: info | warning | error | success
	ShowToast(ctx context.Context, in *ShowToastRequest, opts ...grpc.CallOption) (*ShowToastResponse, error)
	// 只读会话摘要 (与资源管理器一致), JSON 数组。
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	// 插件推送 UI 事件(流式结果/状态变化等)。宿主以 "plugin-event" 事件
	// 转发到前端并按插件分发(前端 ctx.onEvent 订阅)。payload 为任意 JSON。
	EmitUIEvent(ctx context.Context, in *EmitUIEventRequest, opts ...grpc.CallOption) (*EmitUIEventResponse, error)
}

type hostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServiceClient(cc grpc.ClientConnInterface) HostServiceClient {
	return &hostServiceClient{cc}
}

func (c *hostServiceClient) OpenTab(ctx context.Context, in *OpenTabRequest, opts ...grpc.CallOption) (*OpenTabResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenTabResponse)
	err := c.cc.Invoke(ctx, HostService_OpenTab_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) CloseTab(ctx context.Context, in *CloseTabRequest, opts ...grpc.CallOption) (*CloseTabResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseTabResponse)
	err := c.cc.Invoke(ctx, HostService_CloseTab_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) SetTabTitle(ctx context.Context, in *SetTabTitleRequest, opts ...grpc.CallOption) (*SetTabTitleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTabTitleResponse)
	err := c.cc.Invoke(ctx, HostService_SetTabTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) ShowToast(ctx context.Context, in *ShowToastRequest, opts ...grpc.CallOption) (*ShowToastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowToastResponse)
	err := c.cc.Invoke(ctx, HostService_ShowToast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, HostService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) EmitUIEvent(ctx context.Context, in *EmitUIEventRequest, opts ...grpc.CallOption) (*EmitUIEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitUIEventResponse)
	err := c.cc.Invoke(ctx, HostService_EmitUIEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServiceServer is the server API for HostService service.
// All implementations must embed UnimplementedHostServiceServer
// for forward compatibility.
type HostServiceServer interface {
	// 打开标签页 (tabKey 幂等: 已存在则激活并返回现有 ID)。
	// 组件 componentId 必须是插件前端 entry.js 导出 components 中的键。
	OpenTab(context.Context, *OpenTabRequest) (*OpenTabResponse, error)
	// 按 tabKey 关闭标签页。返回是否找到并已请求关闭。
	CloseTab(context.Context, *CloseTabRequest) (*CloseTabResponse, error)
	SetTabTitle(context.Context, *SetTabTitleRequest) (*SetTabTitleResponse, error)
	// 宿主内 Toast 提示。level: info | warning | error | success
	ShowToast(context.Context, *ShowToastRequest) (*ShowToastResponse, error)
	// 只读会话摘要 (与资源管理器一致), JSON 数组。
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	// 插件推送 UI 事件(流式结果/状态变化等)。宿主以 "plugin-event" 事件
	// 转发到前端并按插件分发(前端 ctx.onEvent 订阅)。payload 为任意 JSON。
	EmitUIEvent(context.Context, *EmitUIEventRequest) (*EmitUIEventResponse, error)
	mustEmbedUnimplementedHostServiceServer()
}

// UnimplementedHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServiceServer struct{}

func (UnimplementedHostServiceServer) OpenTab(context.Context, *OpenTabRequest) (*OpenTabResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenTab not implemented")
}
func (UnimplementedHostServiceServer) CloseTab(context.Context, *CloseTabRequest) (*CloseTabResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseTab not implemented")
}
func (UnimplementedHostServiceServer) SetTabTitle(context.Context, *SetTabTitleRequest) (*SetTabTitleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTabTitle not implemented")
}
func (UnimplementedHostServiceServer) ShowToast(context.Context, *ShowToastRequest) (*ShowToastResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShowToast not implemented")
}
func (UnimplementedHostServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedHostServiceServer) EmitUIEvent(context.Context, *EmitUIEventRequest) (*EmitUIEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmitUIEvent not implemented")
}
func (UnimplementedHostServiceServer) mustEmbedUnimplementedHostServiceServer() {}
func (UnimplementedHostServiceServer) testEmbeddedByValue()                     {}

// UnsafeHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServiceServer will
// result in compilation errors.
type UnsafeHostServiceServer interface {
	mustEmbedUnimplementedHostServiceServer()
}

func RegisterHostServiceServer(s grpc.ServiceRegistrar, srv HostServiceServer) {
	// If the following call panics, it indicates UnimplementedHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostService_ServiceDesc, srv)
}

func _HostService_OpenTab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenTabRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).OpenTab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_OpenTab_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).OpenTab(ctx, req.(*OpenTabRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_CloseTab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseTabRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).CloseTab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_CloseTab_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).CloseTab(ctx, req.(*CloseTabRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_SetTabTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTabTitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).SetTabTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_SetTabTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).SetTabTitle(ctx, req.(*SetTabTitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_ShowToast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowToastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).ShowToast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_ShowToast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).ShowToast(ctx, req.(*ShowToastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_EmitUIEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitUIEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).EmitUIEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_EmitUIEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).EmitUIEvent(ctx, req.(*EmitUIEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostService_ServiceDesc is the grpc.ServiceDesc for HostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aceshell.plugin.v1.HostService",
	HandlerType: (*HostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenTab",
			Handler:    _HostService_OpenTab_Handler,
		},
		{
			MethodName: "CloseTab",
			Handler:    _HostService_CloseTab_Handler,
		},
		{
			MethodName: "SetTabTitle",
			Handler:    _HostService_SetTabTitle_Handler,
		},
		{
			MethodName: "ShowToast",
			Handler:    _HostService_ShowToast_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _HostService_ListSessions_Handler,
		},
		{
			MethodName: "EmitUIEvent",
			Handler:    _HostService_EmitUIEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aceshell.proto",
}
