// AceShell 插件协议 v1 —— 跨语言契约 (Go / 其他语言经 gRPC 实现)
//
// 双向服务:
//   - AcePlugin  : 插件进程实现, 宿主调用 (钩子: 生命周期/侧栏显隐/标签页事件/通用 Rpc)
//   - HostService: 宿主进程实现, 插件调用 (能力: 开/关标签页/改标题/Toast/会话清单)
//
// 非宿主侧鉴权: 插件调用 HostService 时须携带 metadata "x-aceshell-token"
// (Start 时由宿主下发的一次性随机令牌)。
//
// 重新生成 (仅协议变更时):
//   go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.12
//   go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
//   go install github.com/bufbuild/buf/cmd/buf@latest
//   buf generate proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: aceshell.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 宿主当前界面语言 (BCP-47, 如 zh-CN / en-US)。插件应据此返回本地化的
	// display_name / views 标题; 不支持该语言时返回默认文案。
	Locale        string `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_aceshell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{0}
}

func (x *InfoRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type PluginInfo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                      // 插件唯一 ID (须与安装目录名一致), [a-z0-9-]
	DisplayName string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // 显示名
	Version     string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Icon        string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`                                  // 侧栏图标: SVG 文本或 dataURI (image/svg+xml / image/png)
	AccentColor string                 `protobuf:"bytes,5,opt,name=accent_color,json=accentColor,proto3" json:"accent_color,omitempty"` // 可选主题色 (CSS color), 用于标签页着色等
	Views       []*ViewInfo            `protobuf:"bytes,6,rep,name=views,proto3" json:"views,omitempty"`
	// 插件声明的能力标签 (可选, 如 "terminal" / "fs" / "net"), 供宿主展示与未来按能力门控。
	Capabilities  []string `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_aceshell_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *PluginInfo) GetAccentColor() string {
	if x != nil {
		return x.AccentColor
	}
	return ""
}

func (x *PluginInfo) GetViews() []*ViewInfo {
	if x != nil {
		return x.Views
	}
	return nil
}

func (x *PluginInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type LocaleChangedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locale        string                 `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"` // 新界面语言 (BCP-47)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocaleChangedRequest) Reset() {
	*x = LocaleChangedRequest{}
	mi := &file_aceshell_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocaleChangedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocaleChangedRequest) ProtoMessage() {}

func (x *LocaleChangedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocaleChangedRequest.ProtoReflect.Descriptor instead.
func (*LocaleChangedRequest) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{2}
}

func (x *LocaleChangedRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type LocaleChangedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocaleChangedResponse) Reset() {
	*x = LocaleChangedResponse{}
	mi := &file_aceshell_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocaleChangedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocaleChangedResponse) ProtoMessage() {}

func (x *LocaleChangedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocaleChangedResponse.ProtoReflect.Descriptor instead.
func (*LocaleChangedResponse) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{3}
}

type ViewInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                      // 视图 ID (插件内唯一)
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                // 侧栏 tooltip 与面板标题
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`                                  // SVG 文本或 dataURI
	ComponentId   string                 `protobuf:"bytes,4,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"` // 插件前端 entry.js 导出 components 中的键
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewInfo) Reset() {
	*x = ViewInfo{}
	mi := &file_aceshell_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewInfo) ProtoMessage() {}

func (x *ViewInfo) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewInfo.ProtoReflect.Descriptor instead.
func (*ViewInfo) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{4}
}

func (x *ViewInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ViewInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ViewInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ViewInfo) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostVersion   string                 `protobuf:"bytes,1,opt,name=host_version,json=hostVersion,proto3" json:"host_version,omitempty"`
	DataDir       string                 `protobuf:"bytes,2,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`                // 插件私有数据目录 (宿主保证存在)
	HostEndpoint  string                 `protobuf:"bytes,3,opt,name=host_endpoint,json=hostEndpoint,proto3" json:"host_endpoint,omitempty"` // HostService gRPC 端点, 127.0.0.1:port
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`                                   // 调用 HostService 时放入 metadata "x-aceshell-token"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_aceshell_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{5}
}

func (x *StartRequest) GetHostVersion() string {
	if x != nil {
		return x.HostVersion
	}
	return ""
}

func (x *StartRequest) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

func (x *StartRequest) GetHostEndpoint() string {
	if x != nil {
		return x.HostEndpoint
	}
	return ""
}

func (x *StartRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_aceshell_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{6}
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_aceshell_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{7}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_aceshell_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{8}
}

type ViewVisibleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewId        string                 `protobuf:"bytes,1,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewVisibleRequest) Reset() {
	*x = ViewVisibleRequest{}
	mi := &file_aceshell_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewVisibleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewVisibleRequest) ProtoMessage() {}

func (x *ViewVisibleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewVisibleRequest.ProtoReflect.Descriptor instead.
func (*ViewVisibleRequest) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{9}
}

func (x *ViewVisibleRequest) GetViewId() string {
	if x != nil {
		return x.ViewId
	}
	return ""
}

type ViewVisibleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewVisibleResponse) Reset() {
	*x = ViewVisibleResponse{}
	mi := &file_aceshell_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewVisibleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewVisibleResponse) ProtoMessage() {}

func (x *ViewVisibleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewVisibleResponse.ProtoReflect.Descriptor instead.
func (*ViewVisibleResponse) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{10}
}

type ViewHiddenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewId        string                 `protobuf:"bytes,1,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewHiddenRequest) Reset() {
	*x = ViewHiddenRequest{}
	mi := &file_aceshell_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewHiddenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewHiddenRequest) ProtoMessage() {}

func (x *ViewHiddenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewHiddenRequest.ProtoReflect.Descriptor instead.
func (*ViewHiddenRequest) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{11}
}

func (x *ViewHiddenRequest) GetViewId() string {
	if x != nil {
		return x.ViewId
	}
	return ""
}

type ViewHiddenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewHiddenResponse) Reset() {
	*x = ViewHiddenResponse{}
	mi := &file_aceshell_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewHiddenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewHiddenResponse) ProtoMessage() {}

func (x *ViewHiddenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewHiddenResponse.ProtoReflect.Descriptor instead.
func (*ViewHiddenResponse) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{12}
}

type TabEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TabKey        string                 `protobuf:"bytes,1,opt,name=tab_key,json=tabKey,proto3" json:"tab_key,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // "opened" | "activated" | "closed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabEvent) Reset() {
	*x = TabEvent{}
	mi := &file_aceshell_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabEvent) ProtoMessage() {}

func (x *TabEvent) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabEvent.ProtoReflect.Descriptor instead.
func (*TabEvent) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{13}
}

func (x *TabEvent) GetTabKey() string {
	if x != nil {
		return x.TabKey
	}
	return ""
}

func (x *TabEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type TabEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabEventResponse) Reset() {
	*x = TabEventResponse{}
	mi := &file_aceshell_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabEventResponse) ProtoMessage() {}

func (x *TabEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabEventResponse.ProtoReflect.Descriptor instead.
func (*TabEventResponse) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{14}
}

type RpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	ArgsJson      string                 `protobuf:"bytes,2,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRequest) Reset() {
	*x = RpcRequest{}
	mi := &file_aceshell_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequest) ProtoMessage() {}

func (x *RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequest.ProtoReflect.Descriptor instead.
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{15}
}

func (x *RpcRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RpcRequest) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

type RpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    string                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"` // 成功时为 JSON 结果 (无内容填 "{}")
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                             // 失败时非空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResponse) Reset() {
	*x = RpcResponse{}
	mi := &file_aceshell_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponse) ProtoMessage() {}

func (x *RpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponse.ProtoReflect.Descriptor instead.
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{16}
}

func (x *RpcResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *RpcResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type OpenTabRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *TabSpec               `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTabRequest) Reset() {
	*x = OpenTabRequest{}
	mi := &file_aceshell_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTabRequest) ProtoMessage() {}

func (x *OpenTabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTabRequest.ProtoReflect.Descriptor instead.
func (*OpenTabRequest) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{17}
}

func (x *OpenTabRequest) GetSpec() *TabSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type OpenTabResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TabId         string                 `protobuf:"bytes,1,opt,name=tab_id,json=tabId,proto3" json:"tab_id,omitempty"` // 确定性 ID: plugin://<插件ID>/<tabKey>
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTabResponse) Reset() {
	*x = OpenTabResponse{}
	mi := &file_aceshell_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTabResponse) ProtoMessage() {}

func (x *OpenTabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTabResponse.ProtoReflect.Descriptor instead.
func (*OpenTabResponse) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{18}
}

func (x *OpenTabResponse) GetTabId() string {
	if x != nil {
		return x.TabId
	}
	return ""
}

type TabSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TabKey        string                 `protobuf:"bytes,1,opt,name=tab_key,json=tabKey,proto3" json:"tab_key,omitempty"` // 插件内唯一键, 幂等去重依据
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ComponentId   string                 `protobuf:"bytes,3,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	PropsJson     string                 `protobuf:"bytes,4,opt,name=props_json,json=propsJson,proto3" json:"props_json,omitempty"` // 传给组件的 props (JSON 对象)
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`                            // 可选, SVG 文本或 dataURI
	Color         string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`                          // 可选, CSS color
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabSpec) Reset() {
	*x = TabSpec{}
	mi := &file_aceshell_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabSpec) ProtoMessage() {}

func (x *TabSpec) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabSpec.ProtoReflect.Descriptor instead.
func (*TabSpec) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{19}
}

func (x *TabSpec) GetTabKey() string {
	if x != nil {
		return x.TabKey
	}
	return ""
}

func (x *TabSpec) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TabSpec) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *TabSpec) GetPropsJson() string {
	if x != nil {
		return x.PropsJson
	}
	return ""
}

func (x *TabSpec) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *TabSpec) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type CloseTabRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TabKey        string                 `protobuf:"bytes,1,opt,name=tab_key,json=tabKey,proto3" json:"tab_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTabRequest) Reset() {
	*x = CloseTabRequest{}
	mi := &file_aceshell_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTabRequest) ProtoMessage() {}

func (x *CloseTabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTabRequest.ProtoReflect.Descriptor instead.
func (*CloseTabRequest) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{20}
}

func (x *CloseTabRequest) GetTabKey() string {
	if x != nil {
		return x.TabKey
	}
	return ""
}

type CloseTabResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Closed        bool                   `protobuf:"varint,1,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTabResponse) Reset() {
	*x = CloseTabResponse{}
	mi := &file_aceshell_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTabResponse) ProtoMessage() {}

func (x *CloseTabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTabResponse.ProtoReflect.Descriptor instead.
func (*CloseTabResponse) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{21}
}

func (x *CloseTabResponse) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

type SetTabTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TabKey        string                 `protobuf:"bytes,1,opt,name=tab_key,json=tabKey,proto3" json:"tab_key,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTabTitleRequest) Reset() {
	*x = SetTabTitleRequest{}
	mi := &file_aceshell_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTabTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTabTitleRequest) ProtoMessage() {}

func (x *SetTabTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTabTitleRequest.ProtoReflect.Descriptor instead.
func (*SetTabTitleRequest) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{22}
}

func (x *SetTabTitleRequest) GetTabKey() string {
	if x != nil {
		return x.TabKey
	}
	return ""
}

func (x *SetTabTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type SetTabTitleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTabTitleResponse) Reset() {
	*x = SetTabTitleResponse{}
	mi := &file_aceshell_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTabTitleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTabTitleResponse) ProtoMessage() {}

func (x *SetTabTitleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTabTitleResponse.ProtoReflect.Descriptor instead.
func (*SetTabTitleResponse) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{23}
}

type ShowToastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowToastRequest) Reset() {
	*x = ShowToastRequest{}
	mi := &file_aceshell_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowToastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowToastRequest) ProtoMessage() {}

func (x *ShowToastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowToastRequest.ProtoReflect.Descriptor instead.
func (*ShowToastRequest) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{24}
}

func (x *ShowToastRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ShowToastRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type ShowToastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowToastResponse) Reset() {
	*x = ShowToastResponse{}
	mi := &file_aceshell_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowToastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowToastResponse) ProtoMessage() {}

func (x *ShowToastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowToastResponse.ProtoReflect.Descriptor instead.
func (*ShowToastResponse) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{25}
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_aceshell_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{26}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionsJson  string                 `protobuf:"bytes,1,opt,name=sessions_json,json=sessionsJson,proto3" json:"sessions_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_aceshell_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{27}
}

func (x *ListSessionsResponse) GetSessionsJson() string {
	if x != nil {
		return x.SessionsJson
	}
	return ""
}

type EmitUIEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayloadJson   string                 `protobuf:"bytes,1,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitUIEventRequest) Reset() {
	*x = EmitUIEventRequest{}
	mi := &file_aceshell_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitUIEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitUIEventRequest) ProtoMessage() {}

func (x *EmitUIEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitUIEventRequest.ProtoReflect.Descriptor instead.
func (*EmitUIEventRequest) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{28}
}

func (x *EmitUIEventRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type EmitUIEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitUIEventResponse) Reset() {
	*x = EmitUIEventResponse{}
	mi := &file_aceshell_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitUIEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitUIEventResponse) ProtoMessage() {}

func (x *EmitUIEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aceshell_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitUIEventResponse.ProtoReflect.Descriptor instead.
func (*EmitUIEventResponse) Descriptor() ([]byte, []int) {
	return file_aceshell_proto_rawDescGZIP(), []int{29}
}

var File_aceshell_proto protoreflect.FileDescriptor

const file_aceshell_proto_rawDesc = "" +
	"\n" +
	"\x0eaceshell.proto\x12\x12aceshell.plugin.v1\"%\n" +
	"\vInfoRequest\x12\x16\n" +
	"\x06locale\x18\x01 \x01(\tR\x06locale\"\xe8\x01\n" +
	"\n" +
	"PluginInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12!\n" +
	"\faccent_color\x18\x05 \x01(\tR\vaccentColor\x122\n" +
	"\x05views\x18\x06 \x03(\v2\x1c.aceshell.plugin.v1.ViewInfoR\x05views\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\".\n" +
	"\x14LocaleChangedRequest\x12\x16\n" +
	"\x06locale\x18\x01 \x01(\tR\x06locale\"\x17\n" +
	"\x15LocaleChangedResponse\"g\n" +
	"\bViewInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12!\n" +
	"\fcomponent_id\x18\x04 \x01(\tR\vcomponentId\"\x87\x01\n" +
	"\fStartRequest\x12!\n" +
	"\fhost_version\x18\x01 \x01(\tR\vhostVersion\x12\x19\n" +
	"\bdata_dir\x18\x02 \x01(\tR\adataDir\x12#\n" +
	"\rhost_endpoint\x18\x03 \x01(\tR\fhostEndpoint\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"\x0f\n" +
	"\rStartResponse\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"-\n" +
	"\x12ViewVisibleRequest\x12\x17\n" +
	"\aview_id\x18\x01 \x01(\tR\x06viewId\"\x15\n" +
	"\x13ViewVisibleResponse\",\n" +
	"\x11ViewHiddenRequest\x12\x17\n" +
	"\aview_id\x18\x01 \x01(\tR\x06viewId\"\x14\n" +
	"\x12ViewHiddenResponse\"7\n" +
	"\bTabEvent\x12\x17\n" +
	"\atab_key\x18\x01 \x01(\tR\x06tabKey\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\"\x12\n" +
	"\x10TabEventResponse\"A\n" +
	"\n" +
	"RpcRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x1b\n" +
	"\targs_json\x18\x02 \x01(\tR\bargsJson\"D\n" +
	"\vRpcResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"A\n" +
	"\x0eOpenTabRequest\x12/\n" +
	"\x04spec\x18\x01 \x01(\v2\x1b.aceshell.plugin.v1.TabSpecR\x04spec\"(\n" +
	"\x0fOpenTabResponse\x12\x15\n" +
	"\x06tab_id\x18\x01 \x01(\tR\x05tabId\"\xa4\x01\n" +
	"\aTabSpec\x12\x17\n" +
	"\atab_key\x18\x01 \x01(\tR\x06tabKey\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\fcomponent_id\x18\x03 \x01(\tR\vcomponentId\x12\x1d\n" +
	"\n" +
	"props_json\x18\x04 \x01(\tR\tpropsJson\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\"*\n" +
	"\x0fCloseTabRequest\x12\x17\n" +
	"\atab_key\x18\x01 \x01(\tR\x06tabKey\"*\n" +
	"\x10CloseTabResponse\x12\x16\n" +
	"\x06closed\x18\x01 \x01(\bR\x06closed\"C\n" +
	"\x12SetTabTitleRequest\x12\x17\n" +
	"\atab_key\x18\x01 \x01(\tR\x06tabKey\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"\x15\n" +
	"\x13SetTabTitleResponse\"B\n" +
	"\x10ShowToastRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\"\x13\n" +
	"\x11ShowToastResponse\"\x15\n" +
	"\x13ListSessionsRequest\";\n" +
	"\x14ListSessionsResponse\x12#\n" +
	"\rsessions_json\x18\x01 \x01(\tR\fsessionsJson\"7\n" +
	"\x12EmitUIEventRequest\x12!\n" +
	"\fpayload_json\x18\x01 \x01(\tR\vpayloadJson\"\x15\n" +
	"\x13EmitUIEventResponse2\xbc\x05\n" +
	"\tAcePlugin\x12G\n" +
	"\x04Info\x12\x1f.aceshell.plugin.v1.InfoRequest\x1a\x1e.aceshell.plugin.v1.PluginInfo\x12L\n" +
	"\x05Start\x12 .aceshell.plugin.v1.StartRequest\x1a!.aceshell.plugin.v1.StartResponse\x12U\n" +
	"\bShutdown\x12#.aceshell.plugin.v1.ShutdownRequest\x1a$.aceshell.plugin.v1.ShutdownResponse\x12`\n" +
	"\rOnViewVisible\x12&.aceshell.plugin.v1.ViewVisibleRequest\x1a'.aceshell.plugin.v1.ViewVisibleResponse\x12]\n" +
	"\fOnViewHidden\x12%.aceshell.plugin.v1.ViewHiddenRequest\x1a&.aceshell.plugin.v1.ViewHiddenResponse\x12P\n" +
	"\n" +
	"OnTabEvent\x12\x1c.aceshell.plugin.v1.TabEvent\x1a$.aceshell.plugin.v1.TabEventResponse\x12F\n" +
	"\x03Rpc\x12\x1e.aceshell.plugin.v1.RpcRequest\x1a\x1f.aceshell.plugin.v1.RpcResponse\x12f\n" +
	"\x0fOnLocaleChanged\x12(.aceshell.plugin.v1.LocaleChangedRequest\x1a).aceshell.plugin.v1.LocaleChangedResponse2\xb5\x04\n" +
	"\vHostService\x12R\n" +
	"\aOpenTab\x12\".aceshell.plugin.v1.OpenTabRequest\x1a#.aceshell.plugin.v1.OpenTabResponse\x12U\n" +
	"\bCloseTab\x12#.aceshell.plugin.v1.CloseTabRequest\x1a$.aceshell.plugin.v1.CloseTabResponse\x12^\n" +
	"\vSetTabTitle\x12&.aceshell.plugin.v1.SetTabTitleRequest\x1a'.aceshell.plugin.v1.SetTabTitleResponse\x12X\n" +
	"\tShowToast\x12$.aceshell.plugin.v1.ShowToastRequest\x1a%.aceshell.plugin.v1.ShowToastResponse\x12a\n" +
	"\fListSessions\x12'.aceshell.plugin.v1.ListSessionsRequest\x1a(.aceshell.plugin.v1.ListSessionsResponse\x12^\n" +
	"\vEmitUIEvent\x12&.aceshell.plugin.v1.EmitUIEventRequest\x1a'.aceshell.plugin.v1.EmitUIEventResponseB#Z!changeme/pluginsdk/proto;pluginv1b\x06proto3"

var (
	file_aceshell_proto_rawDescOnce sync.Once
	file_aceshell_proto_rawDescData []byte
)

func file_aceshell_proto_rawDescGZIP() []byte {
	file_aceshell_proto_rawDescOnce.Do(func() {
		file_aceshell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aceshell_proto_rawDesc), len(file_aceshell_proto_rawDesc)))
	})
	return file_aceshell_proto_rawDescData
}

var file_aceshell_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_aceshell_proto_goTypes = []any{
	(*InfoRequest)(nil),           // 0: aceshell.plugin.v1.InfoRequest
	(*PluginInfo)(nil),            // 1: aceshell.plugin.v1.PluginInfo
	(*LocaleChangedRequest)(nil),  // 2: aceshell.plugin.v1.LocaleChangedRequest
	(*LocaleChangedResponse)(nil), // 3: aceshell.plugin.v1.LocaleChangedResponse
	(*ViewInfo)(nil),              // 4: aceshell.plugin.v1.ViewInfo
	(*StartRequest)(nil),          // 5: aceshell.plugin.v1.StartRequest
	(*StartResponse)(nil),         // 6: aceshell.plugin.v1.StartResponse
	(*ShutdownRequest)(nil),       // 7: aceshell.plugin.v1.ShutdownRequest
	(*ShutdownResponse)(nil),      // 8: aceshell.plugin.v1.ShutdownResponse
	(*ViewVisibleRequest)(nil),    // 9: aceshell.plugin.v1.ViewVisibleRequest
	(*ViewVisibleResponse)(nil),   // 10: aceshell.plugin.v1.ViewVisibleResponse
	(*ViewHiddenRequest)(nil),     // 11: aceshell.plugin.v1.ViewHiddenRequest
	(*ViewHiddenResponse)(nil),    // 12: aceshell.plugin.v1.ViewHiddenResponse
	(*TabEvent)(nil),              // 13: aceshell.plugin.v1.TabEvent
	(*TabEventResponse)(nil),      // 14: aceshell.plugin.v1.TabEventResponse
	(*RpcRequest)(nil),            // 15: aceshell.plugin.v1.RpcRequest
	(*RpcResponse)(nil),           // 16: aceshell.plugin.v1.RpcResponse
	(*OpenTabRequest)(nil),        // 17: aceshell.plugin.v1.OpenTabRequest
	(*OpenTabResponse)(nil),       // 18: aceshell.plugin.v1.OpenTabResponse
	(*TabSpec)(nil),               // 19: aceshell.plugin.v1.TabSpec
	(*CloseTabRequest)(nil),       // 20: aceshell.plugin.v1.CloseTabRequest
	(*CloseTabResponse)(nil),      // 21: aceshell.plugin.v1.CloseTabResponse
	(*SetTabTitleRequest)(nil),    // 22: aceshell.plugin.v1.SetTabTitleRequest
	(*SetTabTitleResponse)(nil),   // 23: aceshell.plugin.v1.SetTabTitleResponse
	(*ShowToastRequest)(nil),      // 24: aceshell.plugin.v1.ShowToastRequest
	(*ShowToastResponse)(nil),     // 25: aceshell.plugin.v1.ShowToastResponse
	(*ListSessionsRequest)(nil),   // 26: aceshell.plugin.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),  // 27: aceshell.plugin.v1.ListSessionsResponse
	(*EmitUIEventRequest)(nil),    // 28: aceshell.plugin.v1.EmitUIEventRequest
	(*EmitUIEventResponse)(nil),   // 29: aceshell.plugin.v1.EmitUIEventResponse
}
var file_aceshell_proto_depIdxs = []int32{
	4,  // 0: aceshell.plugin.v1.PluginInfo.views:type_name -> aceshell.plugin.v1.ViewInfo
	19, // 1: aceshell.plugin.v1.OpenTabRequest.spec:type_name -> aceshell.plugin.v1.TabSpec
	0,  // 2: aceshell.plugin.v1.AcePlugin.Info:input_type -> aceshell.plugin.v1.InfoRequest
	5,  // 3: aceshell.plugin.v1.AcePlugin.Start:input_type -> aceshell.plugin.v1.StartRequest
	7,  // 4: aceshell.plugin.v1.AcePlugin.Shutdown:input_type -> aceshell.plugin.v1.ShutdownRequest
	9,  // 5: aceshell.plugin.v1.AcePlugin.OnViewVisible:input_type -> aceshell.plugin.v1.ViewVisibleRequest
	11, // 6: aceshell.plugin.v1.AcePlugin.OnViewHidden:input_type -> aceshell.plugin.v1.ViewHiddenRequest
	13, // 7: aceshell.plugin.v1.AcePlugin.OnTabEvent:input_type -> aceshell.plugin.v1.TabEvent
	15, // 8: aceshell.plugin.v1.AcePlugin.Rpc:input_type -> aceshell.plugin.v1.RpcRequest
	2,  // 9: aceshell.plugin.v1.AcePlugin.OnLocaleChanged:input_type -> aceshell.plugin.v1.LocaleChangedRequest
	17, // 10: aceshell.plugin.v1.HostService.OpenTab:input_type -> aceshell.plugin.v1.OpenTabRequest
	20, // 11: aceshell.plugin.v1.HostService.CloseTab:input_type -> aceshell.plugin.v1.CloseTabRequest
	22, // 12: aceshell.plugin.v1.HostService.SetTabTitle:input_type -> aceshell.plugin.v1.SetTabTitleRequest
	24, // 13: aceshell.plugin.v1.HostService.ShowToast:input_type -> aceshell.plugin.v1.ShowToastRequest
	26, // 14: aceshell.plugin.v1.HostService.ListSessions:input_type -> aceshell.plugin.v1.ListSessionsRequest
	28, // 15: aceshell.plugin.v1.HostService.EmitUIEvent:input_type -> aceshell.plugin.v1.EmitUIEventRequest
	1,  // 16: aceshell.plugin.v1.AcePlugin.Info:output_type -> aceshell.plugin.v1.PluginInfo
	6,  // 17: aceshell.plugin.v1.AcePlugin.Start:output_type -> aceshell.plugin.v1.StartResponse
	8,  // 18: aceshell.plugin.v1.AcePlugin.Shutdown:output_type -> aceshell.plugin.v1.ShutdownResponse
	10, // 19: aceshell.plugin.v1.AcePlugin.OnViewVisible:output_type -> aceshell.plugin.v1.ViewVisibleResponse
	12, // 20: aceshell.plugin.v1.AcePlugin.OnViewHidden:output_type -> aceshell.plugin.v1.ViewHiddenResponse
	14, // 21: aceshell.plugin.v1.AcePlugin.OnTabEvent:output_type -> aceshell.plugin.v1.TabEventResponse
	16, // 22: aceshell.plugin.v1.AcePlugin.Rpc:output_type -> aceshell.plugin.v1.RpcResponse
	3,  // 23: aceshell.plugin.v1.AcePlugin.OnLocaleChanged:output_type -> aceshell.plugin.v1.LocaleChangedResponse
	18, // 24: aceshell.plugin.v1.HostService.OpenTab:output_type -> aceshell.plugin.v1.OpenTabResponse
	21, // 25: aceshell.plugin.v1.HostService.CloseTab:output_type -> aceshell.plugin.v1.CloseTabResponse
	23, // 26: aceshell.plugin.v1.HostService.SetTabTitle:output_type -> aceshell.plugin.v1.SetTabTitleResponse
	25, // 27: aceshell.plugin.v1.HostService.ShowToast:output_type -> aceshell.plugin.v1.ShowToastResponse
	27, // 28: aceshell.plugin.v1.HostService.ListSessions:output_type -> aceshell.plugin.v1.ListSessionsResponse
	29, // 29: aceshell.plugin.v1.HostService.EmitUIEvent:output_type -> aceshell.plugin.v1.EmitUIEventResponse
	16, // [16:30] is the sub-list for method output_type
	2,  // [2:16] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_aceshell_proto_init() }
func file_aceshell_proto_init() {
	if File_aceshell_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aceshell_proto_rawDesc), len(file_aceshell_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_aceshell_proto_goTypes,
		DependencyIndexes: file_aceshell_proto_depIdxs,
		MessageInfos:      file_aceshell_proto_msgTypes,
	}.Build()
	File_aceshell_proto = out.File
	file_aceshell_proto_goTypes = nil
	file_aceshell_proto_depIdxs = nil
}
